name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-rafaelmydocker-app .

      # Optional: Add push to Docker Hub/GCR here
      # - name: Push image
      #   run: |
      #     echo "${{ secrets.DOCKER_raph092293 }}" | docker login -u "${{ secrets.DOCKER_virgozKi }}" --password-stdin
      #     docker tag my-rafaelmydocker-app yourusername/my-rafaelmydocker-app:latest
      #     docker push yourusername/my-rafaelmydocker-app:latest
