name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-rafaelmydocker-app .

      # Optional: Uncomment at kumpletuhin para i-push sa Docker Hub
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_rafael092293 }}" | docker login -u "${{ secrets.DOCKER_virgozki }}" --password-stdin
          docker tag my-rafaelmydocker-app raphragos/my-rafaelmydocker-app:latest
          docker push raphragos/my-rafaelmydocker-app:latest
